version: "3"

vars:
  PREFIX: "{{.ROOT_DIR}}/local"

tasks:
  clean:
    desc: Clean the build directory
    cmds:
      - |
        rm -rf {{.ROOT_DIR}}/build/*
        rm -rf {{.ROOT_DIR}}/local {{.ROOT_DIR}}/dav1d {{.ROOT_DIR}}/svt-av1 {{.ROOT_DIR}}/avif

  build-dav1d:
    desc: Build libdav1d
    requires:
      vars: [arch]
    vars:
      REPO_URL: "https://code.videolan.org/videolan/dav1d"
    cmds:
      - |
        export CFLAGS="-arch {{.arch}}"
        export CXXFLAGS="-arch {{.arch}}"
        export LDFLAGS="-arch {{.arch}}"

        git clone {{.REPO_URL}} dav1d
        cd {{.ROOT_DIR}}/dav1d
        meson setup build --prefix={{.PREFIX}} --buildtype release -Ddefault_library=static --cross-file {{.ROOT_DIR}}/meson/macos-{{.arch}}.ini --reconfigure
        ninja -C build
        ninja -C build install

  build-svtav1:
    desc: Build svt-av1
    requires:
      vars: [arch]
    vars:
      REPO_URL: "https://gitlab.com/AOMediaCodec/SVT-AV1"
    cmds:
      - |
        export CFLAGS="-arch {{.arch}}"
        export CXXFLAGS="-arch {{.arch}}"
        export LDFLAGS="-arch {{.arch}}"

        git clone {{.REPO_URL}} svt-av1
        cd {{.ROOT_DIR}}/svt-av1/Build
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX={{.PREFIX}} -DCMAKE_OSX_ARCHITECTURES={{.arch}} ..
        ninja
        ninja install

  build-avif:
    desc: Build avif
    requires:
      vars: [arch]
    vars:
      PKG_CONFIG_PATH: "$HOME/local/lib/pkgconfig"
      REPO_URL: "https://github.com/AOMediaCodec/libavif"
    cmds:
      - |
        export CFLAGS="-arch {{.arch}}"
        export CXXFLAGS="-arch {{.arch}}"
        export LDFLAGS="-arch {{.arch}}"

        git clone {{.REPO_URL}} avif
        mkdir -p {{.ROOT_DIR}}/avif/build
        cd {{.ROOT_DIR}}/avif/build
        cmake -DBUILD_SHARED_LIBS=OFF -DAVIF_BUILD_APPS=OFF -DAVIF_CODEC_DAV1D=SYSTEM -DAVIF_CODEC_SVT=SYSTEM -DAVIF_LIBYUV=LOCAL -DCMAKE_PREFIX_PATH={{.PREFIX}} -DCMAKE_OSX_ARCHITECTURES={{.arch}} ..
        make

  build-macos:
    desc: Build for macOS
    requires:
      vars: [arch]
    cmds:
      - |
        task build-dav1d arch={{.arch}}
        task  build-svtav1 arch={{.arch}}
        task  build-avif arch={{.arch}}
