name: "linux-x64"

runs:
  using: composite
  steps:
    - name: Code checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get install nasm
        mkdir -p $GITHUB_WORKSPACE/static_x64/lib

    - name: Install vcpkg
      shell: bash
      run: |
        git clone https://github.com/microsoft/vcpkg builder
        ./builder/bootstrap-vcpkg.sh

    - name: Build libyuv & dav1d
      shell: bash
      run: |
        ./builder/vcpkg install "libyuv:x64-linux"
        ./builder/vcpkg install "dav1d:x64-linux"

    - name: Build svt-av1
      shell: bash
      run: |
        git clone https://gitlab.com/AOMediaCodec/SVT-AV1 $GITHUB_WORKSPACE/svt-av1_x64

        cd $GITHUB_WORKSPACE/svt-av1_x64/Build
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/svt-av1_x64/local ..
        ninja && ninja install

    - name: Prepare dependencies
      shell: bash
      run: |
        ls -R $GITHUB_WORKSPACE/builder/installed/x64-linux/lib
        ls -R $GITHUB_WORKSPACE/static_x64/lib/

        cp -r $GITHUB_WORKSPACE/builder/installed/x64-linux/include $GITHUB_WORKSPACE/static_x64/include
        cp $GITHUB_WORKSPACE/builder/installed/x64-linux/lib/*.a $GITHUB_WORKSPACE/static_x64/lib/
        
        cp -r $GITHUB_WORKSPACE/svt-av1_x64/local/include/svt-av1 $GITHUB_WORKSPACE/static_x64/include
        cp $GITHUB_WORKSPACE/svt-av1_x64/local/lib/libSvtAv1Enc.a $GITHUB_WORKSPACE/static_x64/lib/libSvtAv1Enc.a

    - name: Build avif
      shell: bash
      run: |
        git clone https://github.com/AOMediaCodec/libavif avif_x64
        
        mkdir -p $GITHUB_WORKSPACE/avif_x64/build
        cd $GITHUB_WORKSPACE/avif_x64/build
        cmake -DBUILD_SHARED_LIBS=OFF -DAVIF_BUILD_APPS=OFF -DAVIF_CODEC_DAV1D=SYSTEM -DAVIF_CODEC_SVT=SYSTEM -DAVIF_LIBYUV=SYSTEM -DCMAKE_PREFIX_PATH=$GITHUB_WORKSPACE/static_x64 ..
        make

    - name: Prepare local
      shell: bash
      run: |
        mv $GITHUB_WORKSPACE/static_x64/lib/libSvtAv1Enc.a $GITHUB_WORKSPACE/static_x64/lib/libsvtav1.a
        cp -r $GITHUB_WORKSPACE/avif_x64/include/avif $GITHUB_WORKSPACE/static_x64/include
        cp $GITHUB_WORKSPACE/avif_x64/build/libavif.a $GITHUB_WORKSPACE/static_x64/lib/libavif.a

    - name: Zip local
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/static_x64
        7z a -tzip -mx=9 $GITHUB_WORKSPACE/static_linux_x64.zip include lib

    - name: Save artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binaries-linux-x64
        path: "*.zip"