name: build-macos

on:
  push:
    tags:
      - "*"

jobs:
  build-darwin:
    runs-on: macos-latest
    env:
      MACOSX_DEPLOYMENT_TARGET: 14
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Create macOS binaries
        uses: ./.github/actions/macos-all