name: "macos-all"

runs:
  using: composite
  steps:
    - name: Code checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      shell: bash
      run: |
        brew install nasm
        mkdir -p $GITHUB_WORKSPACE/local_amd64/lib
        mkdir -p $GITHUB_WORKSPACE/local_arm64/lib

    - name: Install vcpkg
      shell: bash
      run: |
        git clone https://github.com/microsoft/vcpkg builder
        ./builder/bootstrap-vcpkg.sh
        cp vcpkg/darwin-amd64-static.cmake builder/triplets/community
        cp vcpkg/darwin-arm64-static.cmake builder/triplets/community

    - name: Build libyuv & dav1d
      shell: bash
      run: |
        ./builder/vcpkg install "libyuv:darwin-amd64-static"
        ./builder/vcpkg install "dav1d:darwin-amd64-static"
        
        ./builder/vcpkg install "libyuv:darwin-arm64-static"
        ./builder/vcpkg install "dav1d:darwin-arm64-static"

    - name: Build svt-av1
      shell: bash
      run: |
        git clone https://gitlab.com/AOMediaCodec/SVT-AV1 $GITHUB_WORKSPACE/svt-av1_amd64
        cp -r $GITHUB_WORKSPACE/svt-av1_amd64 $GITHUB_WORKSPACE/svt-av1_arm64

        cd $GITHUB_WORKSPACE/svt-av1_amd64/Build
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/svt-av1_amd64/local -DCMAKE_OSX_ARCHITECTURES=x86_64 ..
        ninja && ninja install
        
        cd $GITHUB_WORKSPACE/svt-av1_arm64/Build
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/svt-av1_arm64/local -DCMAKE_OSX_ARCHITECTURES=arm64 ..
        ninja && ninja install

    - name: Prepare dependencies
      shell: bash
      run: |
        cp -r $GITHUB_WORKSPACE/builder/installed/darwin-amd64-static/include $GITHUB_WORKSPACE/local_amd64/include
        cp $GITHUB_WORKSPACE/builder/installed/darwin-amd64-static/lib/*.a $GITHUB_WORKSPACE/local_amd64/lib
        
        cp -r $GITHUB_WORKSPACE/builder/installed/darwin-arm64-static/include $GITHUB_WORKSPACE/local_arm64/include
        cp $GITHUB_WORKSPACE/builder/installed/darwin-arm64-static/lib/*.a $GITHUB_WORKSPACE/local_arm64/lib
        
        cp -r $GITHUB_WORKSPACE/svt-av1_amd64/local/include/svt-av1 $GITHUB_WORKSPACE/local_amd64/include
        cp $GITHUB_WORKSPACE/svt-av1_amd64/local/lib/libSvtAv1Enc.a $GITHUB_WORKSPACE/local_amd64/lib/libSvtAv1Enc.a
        
        cp -r $GITHUB_WORKSPACE/svt-av1_arm64/local/include/svt-av1 $GITHUB_WORKSPACE/local_arm64/include
        cp $GITHUB_WORKSPACE/svt-av1_arm64/local/lib/libSvtAv1Enc.a $GITHUB_WORKSPACE/local_arm64/lib/libSvtAv1Enc.a

    - name: Build avif
      shell: bash
      run: |
        git clone https://github.com/AOMediaCodec/libavif avif_amd64
        cp -r $GITHUB_WORKSPACE/avif_amd64 $GITHUB_WORKSPACE/avif_arm64
        
        mkdir -p $GITHUB_WORKSPACE/avif_amd64/build
        cd $GITHUB_WORKSPACE/avif_amd64/build
        cmake -DBUILD_SHARED_LIBS=OFF -DAVIF_BUILD_APPS=OFF -DAVIF_CODEC_DAV1D=SYSTEM -DAVIF_CODEC_SVT=SYSTEM -DAVIF_LIBYUV=SYSTEM -DCMAKE_PREFIX_PATH=$GITHUB_WORKSPACE/local_amd64 -DCMAKE_OSX_ARCHITECTURES=x86_64 ..
        make
        
        mkdir -p $GITHUB_WORKSPACE/avif_arm64/build
        cd $GITHUB_WORKSPACE/avif_arm64/build
        cmake -DBUILD_SHARED_LIBS=OFF -DAVIF_BUILD_APPS=OFF -DAVIF_CODEC_DAV1D=SYSTEM -DAVIF_CODEC_SVT=SYSTEM -DAVIF_LIBYUV=SYSTEM -DCMAKE_PREFIX_PATH=$GITHUB_WORKSPACE/local_arm64 -DCMAKE_OSX_ARCHITECTURES=arm64 ..
        make

    - name: Prepare local
      shell: bash
      run: |
        mv $GITHUB_WORKSPACE/local_amd64/lib/libSvtAv1Enc.a $GITHUB_WORKSPACE/local_amd64/lib/libsvtav1.a
        cp -r $GITHUB_WORKSPACE/avif_amd64/include/avif $GITHUB_WORKSPACE/local_amd64/include
        cp $GITHUB_WORKSPACE/avif_amd64/build/libavif.a $GITHUB_WORKSPACE/local_amd64/lib/libavif.a
        
        mv $GITHUB_WORKSPACE/local_arm64/lib/libSvtAv1Enc.a $GITHUB_WORKSPACE/local_arm64/lib/libsvtav1.a
        cp -r $GITHUB_WORKSPACE/avif_arm64/include/avif $GITHUB_WORKSPACE/local_arm64/include
        cp $GITHUB_WORKSPACE/avif_arm64/build/libavif.a $GITHUB_WORKSPACE/local_arm64/lib/libavif.a

    - name: Zip local
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/local_amd64
        7z a -tzip -mx=9 $GITHUB_WORKSPACE/local_darwin_amd64.zip include lib
        
        cd $GITHUB_WORKSPACE/local_arm64
        7z a -tzip -mx=9 $GITHUB_WORKSPACE/local_darwin_arm64.zip include lib

    - name: Save artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binaries-darwin
        path: "*.zip"